version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/internship_portal
      - JWT_SECRET_KEY=your_secret_key_change_in_production
      - PORT=8000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
