FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
COPY app/ ./app/
COPY wsgi.py .
COPY gunicorn.conf.py .

RUN pip install -r requirements.txt

ENV FLASK_APP=wsgi:app
ENV PYTHONUNBUFFERED=1
ENV PORT=10000

EXPOSE 10000

CMD ["gunicorn", "wsgi:app", "--bind", "0.0.0.0:10000"] 