services:
  - type: web
    name: internship-portal-backend
    env: python
    region: singapore  # Choose the closest region to your users
    buildCommand: chmod +x setup.sh && ./setup.sh
    startCommand: gunicorn "app:app" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/app/uploads
      - key: FLASK_APP
        value: app:app
      - key: PORT
        value: 10000