services:
  - type: web
    name: internship-portal-backend
    env: python
    region: singapore  # Choose the closest region to your users
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/app/uploads/{cv,certifications,announcements}
      chmod -R 755 /opt/render/project/src/app/uploads
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/app/uploads
      - key: FLASK_APP
        value: wsgi:application
      - key: PORT
        value: 10000